# Generated by Django 3.0.2 on 2020-02-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200129_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='tarif',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=18, verbose_name='Тариф'),
            preserve_default=False,
        ),
    ]
