# Generated by Django 3.0.2 on 2020-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configurations_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='countuser',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
